sudo: false
language: python
python: 3.6

env:
  matrix:
   - TOXENV=py27-django111-backendBasic
   - TOXENV=py34-django111-backendBasic
   - TOXENV=py34-django111-backendAllauth
   - TOXENV=py35-django111-backendBasic
   - TOXENV=py35-django111-backendAllauth
   - TOXENV=py36-django111-backendBasic
   - TOXENV=py36-django111-backendAllauth
   # - TOXENV=py34-django20-backendBasic
   # - TOXENV=py34-django20-backendAllauth
   # - TOXENV=py35-django20-backendBasic
   # - TOXENV=py35-django20-backendAllauth
   # - TOXENV=py36-django20-backendBasic
   # - TOXENV=py36-django20-backendAllauth
   - TOXENV=flake8

matrix:
  fast_finish: true
  include:
    - python: "3.5"
      env: TOXENV=py35-django111-backendBasic
    - python: "3.5"
      env: TOXENV=py35-django111-backendAllauth
  exclude:
    - python: "3.6"
      env: TOXENV=py35-django111-backendBasic
    - python: "3.6"
      env: TOXENV=py35-django111-backendAllauth
  allow_failures:
    - env: TOXENV=py35-django111-backendAllauth # Because the exclude above is ignored for some reason
    - env: TOXENV=py35-django111-backendBasic # Because the exclude above is ignored for some reason

cache:
  directories:
    - $HOME/.cache/pip
    - $TRAVIS_BUILD_DIR/.tox

install:
  - pip install --upgrade pip wheel setuptools
  - pip install tox coveralls

branches:
  - devel
  - master

script: tox

after_success:
  - coveralls
